### PR TITLE
Issue #39 and Issue #40 -

### PR DESCRIPTION
**Pull request by amitkris**
Enable Solaris support for go-zfs
Switch from zfs/zpool get to zfs/zpool list for better performance
Signed-off-by: Amit Krishnan <krish.amit@gmail.com>

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/go-zfs/41)

### CODE REVIEW

**Comment by mmlb** [comment]
Hey @amitkris can you rebase on top of master so that we can get correct travis tests (for linux at least)

**Comment by mmlb** [comment]
btw @amitkris thanks for submitting this. I'll take a better look and test this in the next few days.

**Comment by amitkris** [comment]
@mmlb doing the rebase now. 
I tested this using the zfs_test.go on Ubuntu (and Solaris) and they all passed. I had to make a couple of changes in the tests to reflect code changes and this is also a part of the PR.
yw! look forward to your comments.

**Comment by mmlb** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[utils.go, line 97 \[r1\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KC2arS7WdE4D2tvmHKo:-KC2arS7WdE4D2tvmHKp:824455143) ([raw file](https://github.com/mistifyio/go-zfs/blob/597c1a9fd28a677352514bc77ab472b571fe6f90/utils.go#L97)):*
keep the string as one line, also drop the `ZFS` part.

---

*[utils.go, line 101 \[r1\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KC2ccEyL9OEUMdt8_Br:-KC2ccEyL9OEUMdt8_Bs:-868508716) ([raw file](https://github.com/mistifyio/go-zfs/blob/597c1a9fd28a677352514bc77ab472b571fe6f90/utils.go#L101)):*
can you order these by indexes, that way there's some bit of order.

---

*[utils.go, line 278 \[r1\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KC2gma3P9ix0COlV9Gz:-KC2gma3P9ix0COlV9H-:-1510451699) ([raw file](https://github.com/mistifyio/go-zfs/blob/35ad200fe18bfbdf01c3210c0b3800aaf3a174ac/utils.go#L278)):*
put back please

---

*[utils.go, line 301 \[r1\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KC2b11Ja5NJOPKiHQWa:-KC2b11Ja5NJOPKiHQWb:-1999733073) ([raw file](https://github.com/mistifyio/go-zfs/blob/597c1a9fd28a677352514bc77ab472b571fe6f90/utils.go#L301)):*
drop the `Zpool`

---

*[utils_notsolaris.go, line 6 \[r1\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KC2faGKGSKf9NIqBhL8:-KC2faGKGSKf9NIqBhL9:-537995734) ([raw file](https://github.com/mistifyio/go-zfs/blob/597c1a9fd28a677352514bc77ab472b571fe6f90/utils_notsolaris.go#L6)):*
should be `dsPropList` so as to not be exported, ditto with ZpoolPropList

---

*[utils_notsolaris.go, line 6 \[r1\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KC2fz6xf0Rhe1ncFH13:-KC2fz6yeU7IcUacrDC_:-478464612) ([raw file](https://github.com/mistifyio/go-zfs/blob/597c1a9fd28a677352514bc77ab472b571fe6f90/utils_notsolaris.go#L6)):*
I kind of want a `var dsPropListOptions = strings.Join(dsPropList, ",")` to avoid rebuilding the options string given to zpool/zfs.

---

*[utils_notsolaris.go, line 9 \[r1\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KC2bDlnAUU0clQwHTis:-KC2bDloIgvLb4zRvMVQ:-2117098938) ([raw file](https://github.com/mistifyio/go-zfs/blob/597c1a9fd28a677352514bc77ab472b571fe6f90/utils_notsolaris.go#L9)):*
If these are the same they should be put in `zpool.go`

---

*[zfs.go, line 35 \[r1\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KC2gKUSeT1Zfs9XPYas:-KC2gKUSeT1Zfs9XPYat:916639133) ([raw file](https://github.com/mistifyio/go-zfs/blob/35ad200fe18bfbdf01c3210c0b3800aaf3a174ac/zfs.go#L35)):*
what happened to this why was it dropped? Hmm it wasn't being assigned, but that sounds like a bug. Please reinstate and add to the props list.

---

*[zfs_test.go, line 85 \[r1\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KC2bOIMQfFOMffWahuE:-KC2bOIMQfFOMffWahuF:2002068413) ([raw file](https://github.com/mistifyio/go-zfs/blob/597c1a9fd28a677352514bc77ab472b571fe6f90/zfs_test.go#L85)):*
do not split

---

*[zfs_test.go, line 275 \[r1\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KC2da3uZS_q_Z0PzPIx:-KC2da3uZS_q_Z0PzPIy:-740114923) ([raw file](https://github.com/mistifyio/go-zfs/blob/597c1a9fd28a677352514bc77ab472b571fe6f90/zfs_test.go#L275)):*
hmm its not a big deal but I think doing

```
for pool := range pools {
    if pool.Name == "test" {
        // found it
        return
    }
}
t.Fatal("failed to find test zpool")
```

is a bit clearer...

---

*[zpool.go, line 24 \[r1\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KC2f4t_X6N_6IQUzywj:-KC2f4takvV1T6wdaIrb:1654736661) ([raw file](https://github.com/mistifyio/go-zfs/blob/597c1a9fd28a677352514bc77ab472b571fe6f90/zpool.go#L24)):*
this is a NACK. This will break any non-opensource users and makes actually using these values harder. Same for the other (uint64 -> string)s

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/go-zfs/41)*

**Comment by amitkris** [comment]
Hey @mmlb I'm ok with all of your comments (although the uint64 -> string is a real bummer :( ).
Should I just update the PR?

**Comment by mmlb** [comment]
yup update and force-push

**Comment by amitkris** [comment]
@mmlb : I just realized there is one thing that is still an issue. For zpool's if we use list instead of get, -p is an invalid option. If we cannot use -p then we cannot have the Zpool struct elements as integers.
What do you recommend we do?

**Comment by amitkris** [comment]
-p is an invalid option for zpool get as well on Solaris so I will have to use strings to store the zpool elements for Solaris.
I could use zpool get for non-Solaris platforms with a -p so that it doesn't break current compatibility (continue to use uint64's for the zpool struct elements).
Does that work for you?

**Comment by mmlb** [comment]
hmm missing `-p` from `list` is a bummer. Lets continue with `get` then since exact number > human-readable.

See comment about different Zpool structs below.

Also, can you reply to the comments by clicking the `Done` or `Acknowledge` buttons to resolve them.

---

Review status: 0 of 8 files reviewed at latest revision, 13 unresolved discussions.

---

*[zfs_test.go, line 14 \[r3\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KD-HYEcsO-w1Xy0Opud:-KD-HYEcsO-w1Xy0Opue:-534297801) ([raw file](https://github.com/mistifyio/go-zfs/blob/d4a1485b95f6e5c9ac2ec5a23650b362d87fc3e6/zfs_test.go#L14)):*
see http://blog.campoy.cat/2014/03/github-and-go-forking-pull-requests-and.html for how to work with forks of go packages.

---

*[zpool_solaris.go, line 6 \[r3\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KD-G3GNZTpdZqE4wJ1g:-KD-G3GNZTpdZqE4wJ1h:2042774586) ([raw file](https://github.com/mistifyio/go-zfs/blob/d4a1485b95f6e5c9ac2ec5a23650b362d87fc3e6/zpool_solaris.go#L6)):*
having separate structs doesn't make any sense, all consumers are going to have to deal with the multiple formats which defeats the purpose. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-:-KD-CqvAOLJZLfizQZnd:-2143766743)*

**Comment by amitkris** [comment]
Review status: 0 of 8 files reviewed at latest revision, 13 unresolved discussions.

---

*[utils.go, line 97 \[r1\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KC2arS7WdE4D2tvmHKo:-KD-KRGxVHGPBvNirttt:-499146009) ([raw file](https://github.com/mistifyio/go-zfs/blob/597c1a9fd28a677352514bc77ab472b571fe6f90/utils.go#L97)):*
Done.

---

*[utils.go, line 101 \[r1\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KC2ccEyL9OEUMdt8_Br:-KD-KS2Cv6YM917ygqaI:-499146009) ([raw file](https://github.com/mistifyio/go-zfs/blob/597c1a9fd28a677352514bc77ab472b571fe6f90/utils.go#L101)):*
Done.

---

*[utils.go, line 278 \[r1\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KC2gma3P9ix0COlV9Gz:-KD-KCsDhz8XKlZTi0FI:-499146009) ([raw file](https://github.com/mistifyio/go-zfs/blob/35ad200fe18bfbdf01c3210c0b3800aaf3a174ac/utils.go#L278)):*
Done.

---

*[utils.go, line 301 \[r1\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KC2b11Ja5NJOPKiHQWa:-KD-KFuckiF-Sxj2BJDO:-499146009) ([raw file](https://github.com/mistifyio/go-zfs/blob/597c1a9fd28a677352514bc77ab472b571fe6f90/utils.go#L301)):*
Done.

---

*[utils_notsolaris.go, line 6 \[r1\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KC2faGKGSKf9NIqBhL8:-KD-KXaFD2Jj2G4EXmca:-499146009) ([raw file](https://github.com/mistifyio/go-zfs/blob/597c1a9fd28a677352514bc77ab472b571fe6f90/utils_notsolaris.go#L6)):*
Done.

---

*[utils_notsolaris.go, line 6 \[r1\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KC2fz6xf0Rhe1ncFH13:-KD-KYCSsMdk3TMFkPFd:-499146009) ([raw file](https://github.com/mistifyio/go-zfs/blob/597c1a9fd28a677352514bc77ab472b571fe6f90/utils_notsolaris.go#L6)):*
Done.

---

*[utils_notsolaris.go, line 9 \[r1\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KC2bDlnAUU0clQwHTis:-KD-KVx3HSYxGHv2ybXL:-499146009) ([raw file](https://github.com/mistifyio/go-zfs/blob/597c1a9fd28a677352514bc77ab472b571fe6f90/utils_notsolaris.go#L9)):*
Done.

---

*[zfs.go, line 35 \[r1\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KC2gKUSeT1Zfs9XPYas:-KD-K_s3TXPU0echa8Wz:-499146009) ([raw file](https://github.com/mistifyio/go-zfs/blob/35ad200fe18bfbdf01c3210c0b3800aaf3a174ac/zfs.go#L35)):*
Done.

---

*[zfs_test.go, line 85 \[r1\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KC2bOIMQfFOMffWahuE:-KD-KatenyWEmX4wjgbo:-499146009) ([raw file](https://github.com/mistifyio/go-zfs/blob/597c1a9fd28a677352514bc77ab472b571fe6f90/zfs_test.go#L85)):*
Done.

---

*[zfs_test.go, line 275 \[r1\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KC2da3uZS_q_Z0PzPIx:-KD-Kc671OGc69QUOns3:-499146009) ([raw file](https://github.com/mistifyio/go-zfs/blob/597c1a9fd28a677352514bc77ab472b571fe6f90/zfs_test.go#L275)):*
Done.

---

*[zpool.go, line 24 \[r1\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KC2f4t_X6N_6IQUzywj:-KD-Khi1C00xg4aNYKGw:1491352249) ([raw file](https://github.com/mistifyio/go-zfs/blob/597c1a9fd28a677352514bc77ab472b571fe6f90/zpool.go#L24)):*
Updated but needed to split to account for different options on Solaris

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/go-zfs/41)*

**Comment by amitkris** [comment]
-p is not only missing from list it is missing from get as well on Solaris. 

---

Review status: 0 of 8 files reviewed at latest revision, 13 unresolved discussions.

---

*[zpool_solaris.go, line 6 \[r3\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KD-G3GNZTpdZqE4wJ1g:-KD-LnMPM4oK0nlZBupd:-1001666268) ([raw file](https://github.com/mistifyio/go-zfs/blob/d4a1485b95f6e5c9ac2ec5a23650b362d87fc3e6/zpool_solaris.go#L6)):*
In continuation of the above zpool on Solairs does not support the -p option for list OR for get. What do you suggest we do to address this? 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-:-KD-LVIMOV-azIs-bmwF:1020091446)*

**Comment by amitkris** [comment]
Review status: 0 of 8 files reviewed at latest revision, 13 unresolved discussions.

---

*[zfs_test.go, line 14 \[r3\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KD-HYEcsO-w1Xy0Opud:-KD-MTYprjZUYoYPuYJK:551515009) ([raw file](https://github.com/mistifyio/go-zfs/blob/d4a1485b95f6e5c9ac2ec5a23650b362d87fc3e6/zfs_test.go#L14)):*
Aah. Sorry about the oversight. I'll push this fix along with the resolution of the zpool structs issue if thats ok?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/go-zfs/41)*

**Comment by mmlb** [comment]
thats right I forgot to mention, in that case best that can be done is to parse it.

---

Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[zpool_solaris.go, line 6 \[r3\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KD-G3GNZTpdZqE4wJ1g:-KD-QfBfgamq8n5DE7a-:1651469714) ([raw file](https://github.com/mistifyio/go-zfs/blob/d4a1485b95f6e5c9ac2ec5a23650b362d87fc3e6/zpool_solaris.go#L6)):*
I should fire up a vm instead of asking, but since I've got you here... What do the strings look like? The strings should be parse and assigned to the uint64 values, even if they are not exact.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-:-KD-OA34QkIPwIavmMHQ:-94670679)*

**Comment by amitkris** [comment]
the strings are human readable..1.6G, 128M etc. Parsing them will be grossly inaccurate.

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-:-KD-RlQ9URP4Stp0y6jd:1569134568)*

**Comment by mmlb** [comment]
but there's no better recourse so users will just need to know that on solaris based platforms this is the case (for now at least)

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-:-KD-SI3mb8855LhI1k-b:-1910578782)*

**Comment by amitkris** [comment]
hmm..let me try to think of a better way to do this? I really don't want to push the above unless I absolutely have to..I will get back with an updated changeset in a day or two. Is that ok?

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-:-KD-Tdwn6FsK7GNpMeR7:1515602998)*

**Comment by amitkris** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[zpool_solaris.go, line 6 \[r3\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KD-G3GNZTpdZqE4wJ1g:-KD-U9OAegUtJnmu4gaC:1540399456) ([raw file](https://github.com/mistifyio/go-zfs/blob/d4a1485b95f6e5c9ac2ec5a23650b362d87fc3e6/zpool_solaris.go#L6)):*
sorry I just replied above. still getting a hang of this reviewing tool :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/go-zfs/41)*

**Comment by mmlb** [comment]
Sure np.

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[zpool_solaris.go, line 6 \[r3\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KD-G3GNZTpdZqE4wJ1g:-KD-UMoIAleiR-2o8DqN:-460404601) ([raw file](https://github.com/mistifyio/go-zfs/blob/d4a1485b95f6e5c9ac2ec5a23650b362d87fc3e6/zpool_solaris.go#L6)):*
np ;)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-:-KD-SYldD0JpRt34GyUR:634639430)*

**Comment by amitkris** [comment]
@mmlb Sorry for the delay but I patched in a fix to zpool on Solaris so that it now supports "-p".
With that I reverted the changes for zpool on go-zfs to use zpool get as well as to use integer types in the zpool structure as before.
I think this should satisfy all the use cases. Please review when you get the chance.

**Comment by mmlb** [comment]
Reviewed 1 of 7 files at r4.
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[utils.go, line 120 \[r5\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KGDr9l8O3dSom_WOmjF:-KGDr9l8O3dSom_WOmjG:-818377980) ([raw file](https://github.com/mistifyio/go-zfs/blob/271d37bec3e739a223ea774886df3583c5ea025c/utils.go#L120)):*
can you change the logic here to be
```
if runtime.GOOS == "solaris" {
	return nil
}

if err = setUint(&ds.Written, line[9]); err != nil {
	return err
}
if err = setUint(&ds.Logicalused, line[10]); err != nil {
	return err
}
if err = setUint(&ds.Usedbydataset, line[11]); err != nil {
	return err
}
```

---

*[zfs.go, line 37 \[r2\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KGDq2_yUDRnw_xAS4QD:-KGDq2_zt4yan8y6s1xC:1078435779) ([raw file](https://github.com/mistifyio/go-zfs/blob/0726c12bef7cc1c0e150026f80346bd7cd98ba3e/zfs.go#L37)):*
this should be a uint64 also

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistifyio/go-zfs/41)*

**Comment by mmlb** [comment]
Reviewed 1 of 8 files at r2, 1 of 7 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mistifyio/go-zfs/41)*

**Comment by amitkris** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[utils.go, line 120 \[r5\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KGDr9l8O3dSom_WOmjF:-KGDw2ZQeJIh3GQfbFMl:-499146009) ([raw file](https://github.com/mistifyio/go-zfs/blob/271d37bec3e739a223ea774886df3583c5ea025c/utils.go#L120)):*
Done.

---

*[zfs.go, line 37 \[r2\]](https://reviewable.io:443/reviews/mistifyio/go-zfs/41#-KGDq2_yUDRnw_xAS4QD:-KGDvo0n3oSt-EaIZEf2:-1363648510) ([raw file](https://github.com/mistifyio/go-zfs/blob/0726c12bef7cc1c0e150026f80346bd7cd98ba3e/zfs.go#L37)):*
Changed here and correspondingly in parseLine in utils

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistifyio/go-zfs/41)*

**Comment by mmlb** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mistifyio/go-zfs/41)*

**Comment by mmlb** [comment]
Thanks a lot @amitkris this was great. Is there any info on when Oracle Solaris users will be able to use this?

**Comment by amitkris** [comment]
@mmlb: Officlal GO support in Solaris is something new for an upcoming release of Solaris. Once it's there, anyone can use go-zfs.

**Pull request merged**
