### PR TITLE
Switch to google/uuid

### PR DESCRIPTION
**Pull request by justincormack**
No functional change but this is being maintained here now.

Signed-off-by: Justin Cormack <justin.cormack@docker.com>

### CODE REVIEW

**Comment by justincormack** [comment]
(newer versions of `pborman/uuid` are a wrapper around `google/uuid` with some changes, but for this use case these don't matter).

**Comment by thaJeztah** [comment]
ping @Mic92 @mmlb PTAL ❤️

**Comment by Mic92** [comment]
Also the question is if go-zfs really needs uuids in its logging code.

**Comment by thaJeztah** [comment]
Who's able to review/merge this? This would help us get rid of one dependency, and use the same UUID implementation across the board 🤗

**Comment by thaJeztah** [comment]
Thank you!

**Comment by thaJeztah** [comment]
Oh; wondering if a new tagged version is also planned; I see many people switching to Go mod, and having a new tag would help them get the latest changes from master

**Pull request merged**
