### PR TITLE
zfs command uses different order of arguments on freebsd

### PR DESCRIPTION
**Pull request by kvasdopil**
On FreeBSD options for zfs command should follow command name, like "zfs get -t all dataset"

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/go-zfs/32)

### CODE REVIEW

**Comment by bakins** [comment]
Does this still work on Linux?

**Comment by kvasdopil** [comment]
@bakins Not sure how to test it in Linux. On ubuntu 14.04 i'm have installed zfs-fuse (0.7.0-10.1). And zfs get command don't seem to support -t flag i.e. this wasnt even working before.

**Comment by bakins** [comment]
I will test later today. Zfs-fuse is untested and unsupported.

**Comment by bakins** [comment]
@kvasdopil instructions for testing on Linux are in the README

@trisk @mmlb @TauZero I tested this change on Linux and it works.  One of you want to give it a look as well? Thanks!

**Comment by trisk** [comment]
Looks fine. Actually surprised we used `zfs get` with that order, since that's not what `zfs(1M)` says.

**Comment by kvasdopil** [comment]
So can this be merged?

**Comment by TauZero** [comment]
LGTM

**Comment by kvasdopil** [comment]
Can we tag a new version with this commit?

**Comment by TauZero** [comment]
Tagged v2.1.1 https://github.com/mistifyio/go-zfs/releases/tag/v2.1.1

**Pull request merged**
