### PR TITLE
Add test cases for parsing fragmentation line

### LINKED ISSUE #56: "error while getting pool information strconv.ParseUint: parsing "": invalid syntax" in docker info
While installing docker I had a serious problem with my ZFS-Installation. My installation had no fragmentation determination enabled and therefore the command 
```
root@atomic:~# zpool get -p name,health,allocated,size,free,readonly,dedupratio,fragmentation,freeing,leaked tank
NAME  PROPERTY       VALUE    SOURCE
tank  name           tank     -
tank  health         ONLINE   -
tank  allocated      2098558267392  -
tank  size           2989297238016  -
tank  free           890738970624  -
tank  readonly       off      -
tank  dedupratio     1.00x    -
tank  fragmentation  -        -
tank  freeing        0        default
tank  leaked         0        default
```
can not be parsed. the lib struggles with the "-" in fragmentation. This results in the following error message: "Zpool: error while getting pool information strconv.ParseUint: parsing "": invalid syntax"

Original issue in Docker issue trakcer: https://github.com/docker/docker/issues/30551

### PR DESCRIPTION
**Pull request by Mic92**
Fixes #56

### CODE REVIEW

**Comment by Boldie** [comment]
As I remember I had to turn on the spacemap_histogram property to make it working. For now, I can see fragmentation, but I do not know exactly how to reproduce it. A pool created with spacemap_histogram=disabled will be displayed without fragmentation.

**Comment by avnish30jn** [comment]
Are we handling this in the PR ?
```
zpool get -p "name,health,allocated,size,free,readonly,dedupratio,fragmentation,freeing,leaked" apporbit
NAME      PROPERTY       VALUE     SOURCE
apporbit  name           apporbit  -
apporbit  health         ONLINE    -
apporbit  allocated      540672    -
apporbit  size           106837311488  -
apporbit  free           106836770816  -
apporbit  readonly       off       -
apporbit  dedupratio     1.00      -
apporbit  fragmentation  0         -
apporbit  freeing        0         -
apporbit  leaked         0         -
```

**Comment by Mic92** [comment]
Fragmentation is 0, so it should be fine.

**Comment by mmlb** [comment]
Hey @Mic92 I've taken over the PR and changed it to add test for fragmentation. I can't reproduce this issue at all on master. I actually can't find a buggy commit at all, which sucks but this is so old that not worth worrying about I guess.

**Pull request merged**
