### PR TITLE
add zfs mount/unmount

### PR DESCRIPTION
**Pull request by Mic92**
[Review on Reviewable](https://reviewable.io/reviews/mistifyio/go-zfs/31)

### CODE REVIEW

**Comment by bakins** [comment]
Now I wish we had used options structs rather than flags in various places.

**Comment by Mic92** [comment]
how an option struct would look like?

**Comment by bakins** [comment]
For destroy, maybe something like:
```go
type DestroyOptions {
   Recursive bool
   RecursiveClones bool
   ForceUnmount bool 
   DeferDeletion bool
}

func (d *Dataset) Destroy(options * DestroyOptions) error {
    if options == nil {
       options =& DestroyOptions{}
   }
  ...

// user code

err := d.Destroy(&zfs.DestroyOptions{Recursive: true})
 
```

**Comment by Mic92** [comment]
I could still refactor the code in question and also Destroy(), if you are not concerned about backward-compatibility.

**Comment by bakins** [comment]
I used destroy as an example - we may not want to break compatibility now.  For mount maybe:

```go
type MountOptions struct {
    Overlay bool
}

type UnmountOptions struct {
    Force bool
}
```

While it seems like overkill now, we can see what happened with destroy.  Perhaps introduce `DestroyWithOptions` and leave the current `Destroy` as is, just supporting recursive.

**Comment by Mic92** [comment]
I have [implemented](https://github.com/Mic92/docker/commit/4016fe3884610212e90bd8a6922fbd78249fa000) this feature using mount syscall instead, which is much faster for my purpose. At least on linux zfs mount executes the mount userland tool anyway.

**Comment by bakins** [comment]
Thanks.  I may add the calls to `go-zfs` as well. Not 100% sure how it works on other OS's and code would be fairly simple.

Undecided about breaking API for destroy or going with `DestroyWithOptions`. /cc @trisk @xzilla

**Comment by trisk** [comment]
Seems like this would extend logically to `Mount` and replace the `properties` map as well? I think our consumers would be okay with updating that and `Destroy` with a corresponding version bump. I think actual mount/unmount of `mountpoint=legacy` datasets would be outside the scope of `go-zfs`, though.

**Comment by Mic92** [comment]
`mountpoint=legacy` should not be required to use mount(2). This is just used in for docker, to prevent zfs from mounting all docker layers at boot, which is a waste of resources and time.
On Ilumos libzfs uses [mount(2)](https://github.com/illumos/illumos-gate/blob/20afa66e72e7c210ef1f9053d4bc8f5b60d1eeed/usr/src/lib/libzfs/common/libzfs_mount.c#L310), on freebsd it uses [nmount(2)](https://github.com/freebsd/freebsd/blob/01e375543f2cca888435d33af45404f00296ca0c/cddl/compat/opensolaris/misc/zmount.c#L105), on zfsonlinux libzfs uses [mount(8)](https://github.com/zfsonlinux/zfs/blob/master/lib/libzfs/libzfs_mount.c#L279).
nmount(2) has the same behaviour as mount(2), but the parameters are passed different, so mount(2) should work the same way on freebsd. On linux, zfs uses mount(8) even in the kernel, because of license incompatibilities with vfs_mount  (GPL <-> CDDL). I don't know the exact reason, why they cannot use mount(2) in the libzfs, because this could be done without linking against any GPL licensed library.
I wish libzfs_core would be more complete, for example destroy is missing completely.

**Pull request closed without merging**
